name: root
channels:
- conda-forge
- defaults
dependencies:
- flask
- gunicorn
- pandas
- python=3.6
- rdkit
- tensorflow=1.14
- scikit-learn=0.20.2
- scipy
- nomkl
- numpy
- wtforms
- joblib
- pip
- pip:
  - nfp
