name: root
channels:
- conda-forge
- defaults
dependencies:
- flask
- gunicorn
- pandas
- python
- rdkit
- tensorflow>2.0
- scikit-learn=0.23.1
- nomkl
- numpy
- wtforms
- joblib
- pytest
- pip
- pip:
  - nfp==0.1.1
