name: root
channels:
- conda-forge
- defaults
dependencies:
- flask
- gunicorn
- pandas
- python=3.6
- rdkit
- scikit-learn
- scipy
- nomkl
- numpy
- wtforms
- joblib
- tensorflow
- pip
- pip:
  - git+git://github.com/keras-team/keras.git
  - nfp
